application: mail2quip
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: app.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
